# Generated by Django 5.2.13 on 2026-05-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_boo_car_id_a185ef_idx',
            old_name='booking_boo_car_id_f10f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_boo_user_id_dddf68_idx',
            old_name='booking_boo_user_id_7296cb_idx',
        ),
    ]
